In [1]:
from import_dados import *

In [3]:
pessoas = read_pessoas()
sinistros = read_sinistros()
veiculos = read_veiculos()

In [ ]:
colunas_sinistro = ['id_sinistro',
                    'tipo_registro',
                    'data_sinistro',
                    'ano_sinistro',
                    'mes_sinistro',
                    'dia_sinistro',
                    'hora_sinistro',
                    'ano_mes_sinistro',
                    'dia_da_semana',
                    'turno',
                    'logradouro',
                    'numero_logradouro',
                    'tipo_via',
                    'tipo_local',
                    'latitude',
                    'longitude',
                    'cod_ibge',
                    'municipio',
                    'regiao_administrativa',
                    'administracao',
                    'conservacao',
                    'circunscricao']

colunas_pessoa =   ['id_sinistro',
                    'id_pessoa',
                    'id_veiculo',
                    'tipo_veiculo_vitima',
                    'tipo_de_vitima',
                    'modo_transporte_vitima',
                    'sexo',
                    'idade',
                    'gravidade_lesao',
                    'faixa_etaria_demografica',
                    'faixa_etaria_legal',
                    'profissao',
                    'grau_de_instrucao',
                    'nacionalidade',
                    'data_obito',
                    'ano_obito',
                    'mes_obito',
                    'dia_obito',
                    'ano_mes_obito',
                    'local_obito',
                    'local_via',
                    'tempo_sinistro_obito']

colunas_veiculo =  ['id_sinistro',
                    'id_veiculo',
                    'marca_modelo',
                    'ano_fab',
                    'ano_modelo',
                    'cor_veiculo',
                    'tipo_veiculo']

In [30]:
sinistros_pessoas = sinistros.join(
    pessoas.select(colunas_pessoa), 
        on=['id_sinistro']
        )

In [31]:
sinistros_pessoas.filter((pl.col('tipo_registro') == 'SINISTRO FATAL') & (pl.col('gravidade_lesao') == 'NAO DISPONIVEL')).sort('id_sinistro').limit(10)

shape: (10, 71)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_sinist ┆ tipo_regi ┆ data_sini ┆ ano_sinis ┆ … ┆ ano_mes_o ┆ local_obi ┆ local_via ┆ tempo_si │
│ ro        ┆ stro      ┆ stro      ┆ tro       ┆   ┆ bito      ┆ to        ┆ ---       ┆ nistro_o │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ bito     │
│ i64       ┆ str       ┆ str       ┆ i64       ┆   ┆ str       ┆ str       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456308   ┆ SINISTRO  ┆ 09/06/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
sinistros_pessoas.filter(pl.col('id_sinistro') == 2456253)

shape: (10, 71)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_sinist ┆ tipo_regi ┆ data_sini ┆ ano_sinis ┆ … ┆ ano_mes_o ┆ local_obi ┆ local_via ┆ tempo_si │
│ ro        ┆ stro      ┆ stro      ┆ tro       ┆   ┆ bito      ┆ to        ┆ ---       ┆ nistro_o │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ bito     │
│ i64       ┆ str       ┆ str       ┆ i64       ┆   ┆ str       ┆ str       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ 2024/07   ┆ ESTABELEC ┆ PUBLICO   ┆ 0        │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆ IMENTO DE ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ SAUDE     ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2456253   ┆ SINISTRO  ┆ 05/07/202 ┆ 2024      ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null     │
│           ┆ FATAL     ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘